### ISSUE TITLE
Could not load type 'DtronixCommon.Boundary' from assembly 'DtronixCommon, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by gabrielrobert** [Dtronix/DtronixPdf#10]
We are trying to render a page and store it in a memory stream.

We use `DtronixPdf 1.1.2` and `DtronixPdf.ImageSharp 1.1.0`.

```C#
using (var drawing = PdfDocument.Load(path, null))
{
    using (var page = drawing.GetPage(0))
    {
        var largestSideSize = page.Width > page.Height ? page.Width : page.Height;
        var maxWidth = 8192;
        var scale = maxWidth / largestSideSize;

        var result = page.Render(new PdfPageRenderConfig()
        {
            Scale = scale,
            BackgroundColor = Color.White.ToPixel<Argb32>().Argb,
            Viewport = new BoundaryF(0, 0, page.Width * scale, page.Height * scale)
        });

        await result.GetImage().SaveAsync(memoryStream, new JpegEncoder(), CancellationToken.None);
    }
}
```

However, when we call `result.GetImage()` using the `Dtronix.ImageSharp` package, we get this error:

```
System.TypeLoadException
Could not load type 'DtronixCommon.Boundary' from assembly 'DtronixCommon, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null'.
   at DtronixPdf.ImageSharp.PdfBitmapExtensions.GetImage(PdfBitmap bitmap)
```

If we decompile the `GetImage` method, we can see that it references the `Boundary` class.

![image](https://github.com/Dtronix/DtronixPdf/assets/5783827/8b97536e-0945-4dbc-9372-66eb423d8678)

I don't think this class exists anymore. It is supposed to reference `BoundaryF`. I took a look at the code and there are no references to `Boundary`.

https://github.com/Dtronix/DtronixPdf/blob/master/src/DtronixPdf.ImageSharp/PdfBitmapExtensions.cs#L10

I have copied and pasted the above `GetImage` extension method into my project and it works.

Is it because the `Dtronix.ImageSharp` version has not been bumped and uploaded to NuGet?

Thank you!

**Comment by DJGosnell** [comment]
> Is it because the `Dtronix.ImageSharp` version has not been bumped and uploaded to NuGet?

That is precisely the issue.  Thank you for your detail analysis.  I've released a new v1.1.3 version and pushed the packages to nuget to address this.  Please let me know if there is still an issue with this.
