### ISSUE TITLE
DtronixPdf.ImageSharp for SixLabors.ImageSharp v3?

### ISSUE THREAD

**Issue by Michiel-de-Wolde** [Dtronix/DtronixPdf#11]
Hi, thank you for your work.
Due to a combination with other libraries I have been forced to upgrade from SixLabors.ImageSharp v2 to v3.
This gives an issue with DtronixPdf.ImageSharp,PdfBitmapExtensions.
Calling GetImage gives a method-not-found for WrapMemory.
It asks for the method with signature
(void* pointer, int width, int height).
However SixLabors.ImageSharp v3 no longer contains that method, it offers
(void* pointer, int bufferSizeInBytes, int width, int height).
Is there a solution, have I missed it?
Thank you again
Michiel de Wolde

**Comment by Michiel-de-Wolde** [comment]
Hi Daniel,
I absolutely don't want to be pushy.
Just to ask if there are any plans regarding this issue?
Many thanks, Michiel

**Comment by DJGosnell** [comment]
Six Labors decided to change the license of the project to a dual license with companies which make over 1 Million having to purchase  their commercial license.  This is incompatible with the MIT license this project is currently licensed under.  Currently we are supporting up to the latest V2.* version as those versions are still solely licensed under the [Apache-2.0](https://licenses.nuget.org/Apache-2.0) license.

There are not currently any plans on supporting the V3 versions forward.  I'm sure that there is a method to accomplish this in the newer version of ImageSharp, but I don't have any desire to research it as I can't use it in any of my projects.

That said, the code is extremely simple for the conversion of the byte array to an ImageSharp image and there is 100% an equivalent method in the new v3. I'm jut not going to be investing into it.  If you do find an equivalent method, you are free to link it here for documentation purposes and I can make a note of it in the project.

https://github.com/Dtronix/DtronixPdf/blob/7ddf6b15192c86bbaafae3ef104006dfc1880a66/src/DtronixPdf.ImageSharp/PdfBitmapExtensions.cs#L10

https://sixlabors.com/posts/license-changes/
https://github.com/SixLabors/ImageSharp/discussions/2151

**Comment by Michiel-de-Wolde** [comment]
Hi Daniel,

Fully understandable!
Thank you for the explanation.

Greetings, Michiel

**Comment by Michiel-de-Wolde** [comment]
Solved it by not using PdfBitmap extension method GetImage anymore, with implementation
`Image.WrapMemory<Bgra32>(bitmap.Pointer.ToPointer(), (int)bitmap.Viewport.Width, (int)bitmap.Viewport.Height)`
and using a call in my own code
`Image.WrapMemory<Bgra32>(bitmap.Pointer.ToPointer(), bitmap.Width * bitmap.Height, bitmap.Width, bitmap.Height)`
with a small drawback: I now have to mark my code as _unsafe_, and build my library with _allow unsafe code to compile_.
